### ISSUE TITLE
Definir as Funcionalidades

### ISSUE THREAD

**Issue by Man0Lulu** [Man0Lulu/Pi---frontEnd#1]

**Comment by Man0Lulu** [comment]
* Tela de Login
* Tela do livro escolhido
* Tela Minhas Reservas 
* Tela de inicio
- campo de pesquisa
- barra de navegação
- <footer> suporte

**Comment by edudu4** [comment]
-------Versão Final-------
* Tela de Login
* Tela de Inicio
* Tela de Livro
* Tela de Livros Pesquisados
* Tela de Minhas Reservas
