### ISSUE TITLE
FIGMA - Desenhar Tela de Inicio

### ISSUE THREAD

**Issue by edudu4** [Man0Lulu/Pi---frontEnd#3]

**Comment by Man0Lulu** [comment]
Link:

**Comment by Man0Lulu** [comment]
https://www.figma.com/file/UGg9XnQuyMRuWs2yF3sxXh/Untitled?node-id=0%3A1&t=mq4089uMU7B1cLrE-1

**Comment by Man0Lulu** [comment]
Atualização da tela de inicio: https://www.figma.com/file/UGg9XnQuyMRuWs2yF3sxXh/Untitled?node-id=0%3A1&t=szn1PhTANe7dUgzN-1

**Comment by edudu4** [comment]
Versão Final: https://www.figma.com/file/CqFVjUr51KJM4myJiSX6aD/Untitled?node-id=0%3A1&t=fuSaFm1hb5Wf9fwP-1
